import { NextRequest, NextResponse } from "next/server";

// White-label shareable report (JSON + printable HTML). Agencies can
// fetch ?format=html&brand=Acme to render a client-ready one-pager.
export async function GET(req: NextRequest) {
  const url = req.nextUrl.searchParams.get("url") ?? "https://example.com";
  const brand = req.nextUrl.searchParams.get("brand") ?? "Client";
  const format = req.nextUrl.searchParams.get("format") ?? "json";
  const base = process.env.NEXTAUTH_URL ?? req.nextUrl.origin;
  const audit = await fetch(`${base}/api/audit`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ url }),
  }).then((r) => r.json());

  if (format === "html") {
    const rows = (audit.categories ?? [])
      .map((c: any) => `<tr><td>${c.label}</td><td><b>${c.score}</b>/100</td><td>${(c.fixes ?? []).slice(0, 2).join("<br>")}</td></tr>`)
      .join("");
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${brand} — GEO Report</title>
<style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#111}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;font-size:14px}.hdr{background:#111;color:#fff;padding:24px;border-radius:12px}</style>
</head><body><div class="hdr"><h1>${brand} — AI Visibility Report</h1><p>GEO Score ${audit.overall}/100 (Grade ${audit.grade}) · ${audit.url}</p></div>
<h2>Scores by pillar</h2><table><tr><th>Pillar</th><th>Score</th><th>Top fixes</th></tr>${rows}</table>
<h2>Priority actions</h2><ol>${(audit.topActions ?? []).map((a: any) => `<li><b>${a.title}</b> (${a.impact}) — ${a.detail}</li>`).join("")}</ol>
<p><small>Generated by RankAI GEO · ${new Date().toISOString()}</small></p></body></html>`;
    return new Response(html, { headers: { "Content-Type": "text/html" } });
  }
  return NextResponse.json({ brand, generatedAt: new Date().toISOString(), audit });
}
